const pool = require("../../../../config/db");

// 📌 Punch In
exports.punchIn = async (req, res) => {
  try {
    const { memberId, role } = req.body;

    const now = new Date();
    const date = now.toISOString().split("T")[0];

    // Check if already punched in
    const [exist] = await pool
      .promise()
      .query(
        "SELECT * FROM attendance WHERE memberId=? AND DATE(punchIn)=?",
        [memberId, date]
      );

    if (exist.length > 0) {
      return res.status(400).json({ message: "Already punched in today" });
    }

    // Insert (ID auto-generated by MySQL)
    const [insert] = await pool
      .promise()
      .query(
        "INSERT INTO attendance (memberId, role, punchIn, status) VALUES (?, ?, ?, ?)",
        [memberId, role, now, "Present"]
      );

    // Fetch the inserted row
    const [row] = await pool
      .promise()
      .query("SELECT * FROM attendance WHERE id=?", [insert.insertId]);

    res.json({
      message: "Punched in successfully",
      data: row[0],
    });

  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Punch in failed" });
  }
};

// 📌 Punch Out
exports.punchOut = async (req, res) => {
  try {
    const { recordId } = req.body;
    const now = new Date();

    const [record] = await pool
      .promise()
      .query("SELECT punchIn FROM attendance WHERE id=?", [recordId]);

    if (record.length === 0) {
      return res.status(404).json({ message: "Record not found" });
    }

    const punchIn = new Date(record[0].punchIn);
    const diff = now - punchIn;

    const hours = Math.floor(diff / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));

    const totalHours = `${hours}h ${minutes}m`;

    await pool
      .promise()
      .query(
        "UPDATE attendance SET punchOut=?, totalHours=? WHERE id=?",
        [now, totalHours, recordId]
      );

    res.json({
      message: "Punched out successfully",
      punchOut: now,
      totalHours,
    });

  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Punch out failed" });
  }
};

// 📌 Today's Attendance
exports.getTodayAttendance = async (req, res) => {
  try {
    const { userId } = req.params;
    const date = new Date().toISOString().split("T")[0];

    const [rows] = await pool
      .promise()
      .query(
        "SELECT * FROM attendance WHERE memberId=? AND DATE(punchIn)=?",
        [userId, date]
      );

    res.json(rows[0] || null);

  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Failed to fetch today's attendance" });
  }
};

// 📌 Monthly Attendance
exports.getMonthlyAttendance = async (req, res) => {
  try {
    const { userId, month } = req.params;

    const [rows] = await pool
      .promise()
      .query(
        "SELECT * FROM attendance WHERE memberId=? AND MONTH(punchIn)=? ORDER BY punchIn DESC",
        [userId, month]
      );

    res.json(rows);

  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Failed to fetch monthly attendance" });
  }
};
